# Generated by Django 3.2.12 on 2022-10-27 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('mybasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Product.mybasemodel')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('mobile', models.IntegerField()),
                ('department', models.CharField(max_length=255)),
                ('status', models.BooleanField(max_length=255)),
                ('salary', models.IntegerField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=100)),
            ],
            bases=('Product.mybasemodel',),
        ),
    ]
