# Generated by Django 3.2.12 on 2022-10-28 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='NurseInform',
            fields=[
                ('mybasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Product.mybasemodel')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('educations', models.CharField(max_length=255)),
                ('DOB', models.DateTimeField(auto_now_add=True)),
                ('girls', models.IntegerField()),
                ('boys', models.IntegerField()),
            ],
            bases=('Product.mybasemodel',),
        ),
    ]
