# Generated by Django 3.2.12 on 2022-10-30 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_nurseinform'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalDepartment',
            fields=[
                ('mybasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Product.mybasemodel')),
                ('outpatient_dep', models.IntegerField()),
                ('inpatient_service', models.IntegerField()),
                ('medical_dep', models.IntegerField()),
                ('nursing_dep', models.IntegerField()),
                ('paramedical', models.IntegerField()),
                ('operation_theatre_complex', models.IntegerField()),
                ('pharmacy', models.IntegerField()),
                ('radiology_dep', models.IntegerField()),
                ('non_professional_services', models.IntegerField()),
                ('medical_record_dep', models.IntegerField()),
                ('personnel_dep', models.IntegerField()),
            ],
            bases=('Product.mybasemodel',),
        ),
    ]
