# Generated by Django 3.2.12 on 2022-11-29 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_hospitaldepartment'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalBranch',
            fields=[
                ('mybasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Product.mybasemodel')),
                ('h_name', models.CharField(max_length=255)),
                ('h_city', models.CharField(blank=True, max_length=255)),
                ('no_doctor_present', models.IntegerField()),
                ('no_nurse', models.IntegerField()),
                ('h_ward', models.CharField(blank=True, max_length=255)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('password_code', models.IntegerField()),
            ],
            bases=('Product.mybasemodel',),
        ),
    ]
