# Generated by Django 3.2.12 on 2022-11-08 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Product', '0004_hospitaldepartment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientPayment',
            fields=[
                ('mybasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Product.mybasemodel')),
                ('p_name', models.CharField(blank=True, max_length=255)),
                ('p_address', models.CharField(blank=True, max_length=255)),
                ('medicine_cost', models.IntegerField()),
                ('room_charge', models.IntegerField()),
                ('doctor_free', models.IntegerField()),
                ('other_charge', models.IntegerField()),
                ('total_bill', models.IntegerField()),
            ],
            bases=('Product.mybasemodel',),
        ),
    ]
