# Generated by Django 3.2.12 on 2022-10-27 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Product', '0002_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientView',
            fields=[
                ('mybasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Product.mybasemodel')),
                ('p_id', models.IntegerField()),
                ('patient_name', models.CharField(blank=True, max_length=255)),
                ('assigned_doctor_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('phone_no', models.IntegerField()),
                ('symptoms', models.CharField(max_length=255)),
                ('admit_date', models.DateTimeField(auto_now_add=True)),
                ('release_Date', models.DateTimeField(auto_now_add=True)),
                ('medicine_cost', models.IntegerField()),
                ('room_charge', models.IntegerField()),
                ('doctor_free', models.IntegerField()),
                ('other_charge', models.IntegerField()),
                ('total_bill', models.IntegerField()),
            ],
            bases=('Product.mybasemodel',),
        ),
    ]
