# Generated by Django 3.2.12 on 2022-10-27 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_doctor'),
        ('Patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentPatient',
            fields=[
                ('mybasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Product.mybasemodel')),
                ('doctor_id', models.IntegerField()),
                ('patient_id', models.IntegerField()),
                ('doctor_name', models.CharField(max_length=255)),
                ('patient_name', models.CharField(blank=True, max_length=100)),
                ('discription', models.CharField(blank=True, max_length=255)),
                ('appointment_date', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=255)),
            ],
            bases=('Product.mybasemodel',),
        ),
    ]
