# Generated by Django 3.2.12 on 2022-10-27 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_doctor'),
        ('Patient', '0002_appointmentpatient'),
    ]

    operations = [
        migrations.CreateModel(
            name='DischrgePatient',
            fields=[
                ('mybasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Product.mybasemodel')),
                ('name', models.CharField(max_length=255)),
                ('mobile', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
                ('symptoms', models.CharField(blank=True, max_length=100)),
                ('admin_date', models.DateTimeField(auto_now_add=True)),
                ('day', models.CharField(max_length=255)),
                ('bill', models.IntegerField()),
            ],
            bases=('Product.mybasemodel',),
        ),
        migrations.AlterField(
            model_name='appointmentpatient',
            name='status',
            field=models.BooleanField(max_length=255),
        ),
    ]
