# Generated by Django 3.2.12 on 2022-11-06 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0003_auto_20221027_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('mobile', models.IntegerField()),
                ('department', models.CharField(max_length=255)),
                ('status', models.BooleanField(max_length=255)),
                ('user_no', models.IntegerField()),
            ],
        ),
    ]
