# Generated by Django 3.2.12 on 2022-11-11 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_hospitaldepartment'),
        ('Patient', '0006_auto_20221106_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookApponitment',
            fields=[
                ('mybasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Product.mybasemodel')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('sick', models.CharField(blank=True, max_length=100)),
                ('doctor_name', models.CharField(max_length=100)),
            ],
            bases=('Product.mybasemodel',),
        ),
    ]
